# https://devices.esphome.io/devices/ESP32-CAM

esphome:
  name: camera02
  friendly_name: ESP32-CAM Camera 
  
esp32:
  board: esp32dev
  framework:
    type: arduino

esp32_camera:
  name: "My Cam"
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  max_framerate: 15 fps   
  idle_framerate: 0.05 fps 
  resolution: 1024x768
  jpeg_quality: 35
  
switch:
  - platform: gpio
    name: "My Cam flash"
    pin: 4