# https://devices.esphome.io/devices/Generic-Relay

esphome:
  name: relay01
  friendly_name: Relay ESP32

esp32:
  board: esp32dev
  framework:
    type: arduino

switch:
  - platform: gpio
    name: "Relay 01"
    pin:
      number: GPIO13
      inverted: False