# https://devices.esphome.io/devices/ESP-01S-1-channel-relay

esphome:
  name: relay02
  friendly_name: Relay ESP8266

esp8266:
  board: esp01_1m
  
web_server:
  port: 80

switch:
  - platform: gpio
    pin: GPIO0
    name: "Programador Vir"
    inverted: True
    restore_mode: ALWAYS_OFF
